Add help format string for --ssl_dh_params_file option
Add missing portion of format string for --help output for the --ssl_dh_params_file option.
The absence of this means that there currently are too many arguments for the format string.

$ make
...
../../perdition/options.c:1767:5: warning: format ‘%d’ expects argument of type ‘int’, but argument 34 has type ‘const char *’ [-Wformat=]
1767 | "perdition version %s Copyright Horms\n"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../perdition/options.c:1924:20: note: format string is defined here
1924 | " (default %d)\n"

Signed-off-by: Lukas Karas lukas.karas@avast.com